import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

// ── release signing ─────────────────────────────────────────────────────────
// The upload/release key lives OUTSIDE the repository, in a properties file
// that names the keystore and its passwords:
//   storeFile=..., storePassword=..., keyAlias=..., keyPassword=...
// Its path is RA_SIGNING_PROPS, or the default folder beside the repo. Neither
// the keystore nor that file is ever committed (.gitignore covers both).
//
// On a machine without it (CI, a classmate's laptop) the release build still
// works, signed with the debug key as before, and says so loudly: an APK
// signed that way installs for a demo but can never be updated by, or
// published as, the real release.
val signingPropsFile = file(
    System.getenv("RA_SIGNING_PROPS")?.takeIf { it.isNotBlank() }
        ?: "S:/PROJECTS/RoadAssist-Bharat-signing/keystore.properties",
)
val signingProps = Properties().apply {
    if (signingPropsFile.isFile) signingPropsFile.inputStream().use { load(it) }
}
val hasReleaseKey = listOf("storeFile", "storePassword", "keyAlias", "keyPassword")
    .all { !signingProps.getProperty(it).isNullOrBlank() } &&
    file(signingProps.getProperty("storeFile")).isFile

// ── the SOS ladder's SMS number ─────────────────────────────────────────────
// The SMS rung texts this number, and is switched OFF when it is empty, which
// is the default: no RoadAssist short code is provisioned yet, and texting a
// made-up number could put somebody's emergency and location on a stranger's
// phone. Set it at build time once a real one exists:
//   ./gradlew assembleRelease -PraSmsNumber=+91...
//
// It is a build-config constant, but generated as Kotlin (RaBuildConfig.kt)
// rather than through AGP's buildConfigField: that writes BuildConfig.JAVA,
// the app's only Java source, and compiling Java needs jlink, which the
// JetBrains runtime this project builds with (jbr-21) does not ship.
val raSmsNumber = (project.findProperty("raSmsNumber") as String?)?.trim().orEmpty()
require(raSmsNumber.isEmpty() || Regex("^[+]?[0-9]{3,15}$").matches(raSmsNumber)) {
    "raSmsNumber must be digits, optionally with a leading +"
}

abstract class RaBuildConfigTask : DefaultTask() {
    @get:Input abstract val smsNumber: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun write() {
        val dir = outputDir.get().asFile.resolve("in/roadassist/app").apply { mkdirs() }
        dir.resolve("RaBuildConfig.kt").writeText(
            "package `in`.roadassist.app\n\n" +
                "/** Generated by app/build.gradle.kts (generateRaBuildConfig). Do not edit. */\n" +
                "object RaBuildConfig {\n" +
                "    /** The SOS SMS rung's number; empty switches the rung off (-PraSmsNumber). */\n" +
                "    const val RA_SMS_NUMBER: String = \"" + smsNumber.get() + "\"\n" +
                "}\n",
        )
    }
}

val generateRaBuildConfig = tasks.register<RaBuildConfigTask>("generateRaBuildConfig") {
    smsNumber.set(raSmsNumber)
}

android {
    namespace = "in.roadassist.app"
    // 36 (Android 16) is the newest platform installed here. Raising the
    // target from 35 changed nothing this app relies on: edge-to-edge was
    // already enforced at 35 and every screen pads for the system bars (the
    // app never used the windowOptOutEdgeToEdgeEnforcement escape that 36
    // removes); predictive back is on by default at 36 and already opted into
    // in the manifest, with no onBackPressed override for it to skip; and no
    // activity locks orientation or resizability, which 36 ignores on large
    // screens. Smoke-tested on an API 36 emulator before it was raised.
    compileSdk = 36

    defaultConfig {
        applicationId = "in.roadassist.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 10
        versionName = "1.1.1"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // The on-device road-damage detector (ONNX Runtime) is native code, one
        // copy per CPU type. x86 (32-bit) is left out: no phone sold in years
        // runs it, and each ABI adds megabytes to every download. arm64-v8a
        // is phones; armeabi-v7a is older and Android Go phones that run a
        // 32-bit system on 64-bit hardware; x86_64 is the emulator.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
        }
    }

    // Per-ABI APKs, on request: ./gradlew assembleRelease -PabiSplits
    // (or assembleDebug -PabiSplits for an emulator with little storage).
    // Off by default because AGP refuses to build an App Bundle in the same
    // run as split APKs when resources are shrunk (issuetracker 402800800),
    // and the release build makes both. The default APK is universal: it
    // installs on any of the three ABIs, which is what a file handed round
    // has to do. Play takes the AAB, which delivers only the phone's own ABI.
    splits {
        abi {
            isEnable = project.hasProperty("abiSplits")
            reset()
            include("arm64-v8a", "armeabi-v7a", "x86_64")
            isUniversalApk = true
        }
    }

    signingConfigs {
        if (hasReleaseKey) {
            create("release") {
                storeFile = file(signingProps.getProperty("storeFile"))
                storePassword = signingProps.getProperty("storePassword")
                keyAlias = signingProps.getProperty("keyAlias")
                keyPassword = signingProps.getProperty("keyPassword")
                // v1 for nothing (minSdk 26 verifies v2), v2 + v3 so a future
                // key rotation is possible without a new package name.
                enableV1Signing = false
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            // R8 in optimising mode. This is the single largest smoothness lever
            // available to this app: a debug build runs unoptimised bytecode with
            // Compose's diagnostic paths live, and on this project measured ~25%
            // janky frames against ~4% for the same code built here.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // The real release key when this machine has it (see the top of
            // this file); otherwise the debug key, with a warning, so the
            // build never fails for want of a secret that is not in git.
            signingConfig = if (hasReleaseKey) {
                signingConfigs.getByName("release")
            } else {
                logger.warn(
                    "WARNING: no release signing key at ${signingPropsFile.path} (set RA_SIGNING_PROPS). " +
                        "The release APK/AAB will be signed with the DEBUG key: installable for a demo, " +
                        "NOT release-signed, and not updatable by or publishable as the real release.",
                )
                signingConfigs.getByName("debug")
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
    }

    // ONNX Runtime's native library is ~33 MB per ABI uncompressed and ~13 MB
    // compressed. Stored compressed, the APK a person downloads is about 20 MB
    // smaller; the cost is that Android unpacks it once at install, which is
    // what every app did before API 23.
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    // The detector parity fixtures (written by mobile/tools/
    // detector_parity_reference.py from ai/serve.py) and their reader serve
    // both the JVM test and the on-device one, so they live in one place.
    sourceSets {
        getByName("test").java.srcDir("src/sharedTest/java")
        getByName("androidTest").java.srcDir("src/sharedTest/java")
        getByName("androidTest").assets.srcDir("src/test/resources")
    }

    lint {
        // An error fails the build. The one that was failing — SEND_SMS without
        // a telephony <uses-feature required="false"> — was a real defect: Play
        // would have treated a radio as mandatory and hidden the app from every
        // tablet, which is the opposite of what this product claims.
        abortOnError = true

        // These three compare our pins against whatever is newest on the day the
        // check runs, so they turn CI red when someone ELSE publishes a release
        // and tell us nothing about this commit. Dependency freshness is a
        // deliberate decision with its own cadence, not a build failure.
        disable += setOf("GradleDependency", "NewerVersionAvailable", "AndroidGradlePluginVersion")

        // CI reads the XML; a human reads the HTML.
        xmlReport = true
        htmlReport = true
    }
}

// A debug build is installed over and over on an emulator, whose data
// partition is small; unpacking 33 MB of native code on top of the APK on
// every install is what fills it ("INSUFFICIENT_STORAGE"). Debug keeps the
// library stored uncompressed and mapped in place instead. Release is
// unchanged: compressed, for the smaller download.
androidComponents {
    // RaBuildConfig.kt (the SOS SMS number, above) for every variant.
    onVariants { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(generateRaBuildConfig, RaBuildConfigTask::outputDir)
    }
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.packaging.jniLibs.useLegacyPackaging.set(false)
    }
}

/** ONNX Runtime for Android: runs the scanner's road-damage model on the phone. */
val onnxRuntime = "1.30.0"

dependencies {
    // Deliberately lean: AndroidX + Compose, plus ONNX Runtime for the
    // on-device detector (below) as the one third-party library. Networking
    // uses HttpURLConnection and org.json from the platform.
    val composeBom = platform("androidx.compose:compose-bom:2024.09.03")
    implementation(composeBom)
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.6")

    // JVM unit tests only — never shipped. JUnit 4 rather than 5 because that is
    // what AGP's testDebugUnitTest task runs without extra wiring, and the tests
    // here need nothing JUnit 5 provides.
    testImplementation("junit:junit:4.13.2")
    // A REAL org.json for unit tests only. The Android SDK's org.json is a stub
    // on the JVM classpath — every method throws "not mocked" — so without this
    // the networking layer cannot be tested off-device at all, which is how a
    // concurrency bug in token rotation went unnoticed. Test-only, exactly like
    // JUnit above; the shipped app still uses the platform's own org.json.
    testImplementation("org.json:json:20240303")
    // WindowCompat — flips the status/navigation-bar icon polarity when the
    // in-app light/dark toggle changes. AndroidX, not a third-party library.
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
    // Installs src/main/baseline-prof.txt into ART on first run, so the hot
    // startup and scroll paths are compiled ahead of time instead of being
    // interpreted until the JIT catches up. AndroidX, not a third-party library.
    implementation("androidx.profileinstaller:profileinstaller:1.4.1")

    // ── Scan road: on-device road-damage detection ─────────────────────────
    // CameraX for the preview and the frames, ONNX Runtime to run the RAKSHA
    // YOLO detector on them, entirely on the phone: no network at any point.
    // CameraX 1.5.x is the newest line built against Kotlin 2.0.21, which this
    // project uses (1.6 needs a 2.1 compiler). ONNX Runtime is MIT-licensed and
    // runs the same .onnx file ai/serve.py serves. The full package, because
    // the reduced "mobile" one stopped shipping after 1.15 and needs the model
    // converted to .ort, which would be a second source of truth for the model.
    val cameraX = "1.5.3"
    implementation("androidx.camera:camera-camera2:$cameraX")
    implementation("androidx.camera:camera-lifecycle:$cameraX")
    implementation("androidx.camera:camera-view:$cameraX")
    // A picked photo's EXIF orientation (serve.py's exif_transpose). Already
    // pulled in by CameraX at this version; named because ScanRoad uses it.
    implementation("androidx.exifinterface:exifinterface:1.4.2")
    implementation("com.microsoft.onnxruntime:onnxruntime-android:$onnxRuntime")

    // On-device parity test only (DetectorDeviceParityTest): runs the shipped
    // model through the app's own detector on a phone or emulator. Never shipped.
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
}
